# Generated by Django 6.0.7 on 2026-08-03 04:18

import libros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=libros.models.imagen_path),
        ),
    ]
